### ISSUE TITLE
Not able to get OBO file

### ISSUE THREAD

**Issue by YojanaGadiya** [DIDEO/DIDEO#18]
I was trying to convert the OWL file in the repo to OBO format using the following code:
```
from pronto import Ontology

dideo = 'https://raw.githubusercontent.com/DIDEO/DIDEO/master/dideo.owl'
file_name = dideo.split('/')[-1]
Ontology.from_obo_library(file_name)
```
But when I do so, I get the following error:
```
Traceback (most recent call last):
  File "annotate_assay.py", line 216, in <module>
    main()
  File "annotate_assay.py", line 212, in main
    Ontology.from_obo_library(file_name)
  File "lib\site-packages\pronto\ontology.py", line 206, in from_obo_library
    return cls(
  File "lib\site-packages\pronto\ontology.py", line 283, in __init__
    cls(self).parse_from(_handle)  # type: ignore
  File "lib\site-packages\pronto\parsers\rdfxml.py", line 95, in parse_from
    self.process_imports(
  File "lib\site-packages\pronto\parsers\base.py", line 70, in process_imports
    return dict(pool.map(lambda i: (i, process(i)), imports))
  File "lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "lib\site-packages\pronto\parsers\base.py", line 70, in <lambda>
    return dict(pool.map(lambda i: (i, process(i)), imports))
  File "lib\site-packages\pronto\parsers\base.py", line 49, in process_import
    return Ontology(url, max(import_depth - 1, -1), timeout)
  File "lib\site-packages\pronto\ontology.py", line 283, in __init__
    cls(self).parse_from(_handle)  # type: ignore
  File "lib\site-packages\pronto\parsers\rdfxml.py", line 95, in parse_from
    self.process_imports(
  File "lib\site-packages\pronto\parsers\base.py", line 70, in process_imports
    return dict(pool.map(lambda i: (i, process(i)), imports))
  File "lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "lib\site-packages\pronto\parsers\base.py", line 70, in <lambda>
    return dict(pool.map(lambda i: (i, process(i)), imports))
  File "lib\site-packages\pronto\parsers\base.py", line 49, in process_import
    return Ontology(url, max(import_depth - 1, -1), timeout)
  File "lib\site-packages\pronto\ontology.py", line 283, in __init__
    cls(self).parse_from(_handle)  # type: ignore
  File "lib\site-packages\pronto\parsers\rdfxml.py", line 122, in parse_from
    self.symmetrize_lineage()
  File "lib\site-packages\pronto\parsers\base.py", line 84, in symmetrize_lineage
    graphdata.lineage[superentity].sub.add(subentity)
KeyError: 'http://www.geneontology.org/formats/oboInOwl#ObsoleteClass'
```
I am not sure what the issue is. Is it from the OWL file or something from the pronto package but the aim is to get an OBO file. Do you have any other alternative for doing so?

Thank You.

**Comment by mbrochhausen** [comment]
I think this is a question for the PRONTO developers or the OBO community.
